
name: Android Build CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Set up Flutter
        run: git clone https://github.com/flutter/flutter.git -b stable && ./flutter/bin/flutter precache
      - name: Download OpenCV
        run: |
          curl -L https://sourceforge.net/projects/opencvlibrary/files/4.5.3/opencv-4.5.3-android-sdk.zip/download > opencv-sdk.zip && unzip opencv-sdk.zip
      - name: Set up OpenCV
        run: |
          mkdir -p ~/.gradle && touch ~/.gradle/gradle.properties && echo "opencvsdk=$(pwd)/OpenCV-android-sdk" > ~/.gradle/gradle.properties
      - name: Build with Flutter
        run: |
          cd simple_pdf_scanner && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build appbundle
        env:
          TZ: UTC
